# Makefile 2 
#***************************************************************************
# 
# Java development root directory.
# 
# (C) 1999 Jacob Dreyer - Geotechnical Software Services
# jacob.dreyer@geosoft.no - http://geosoft.no
#
# Modifications Copyright (C) 2001, 2004 Robert Grimm 
# rgrimm@alum.mit.edu
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
#***************************************************************************




#***************************************************************************
#
# This section describes the current package.
#
# o PACKAGE     - The complete package name. 
# o PACKAGE_LOC - Same as PACKAGE but with "/"s instead of "."s.
# o SOURCE      - List of the source files. Remember extension.
# o JNI_SOURCE  - Files from SOURCE that are to be built with the JAVAH 
#                 compiler.
# o JAR_EXTRAS  - None-class files and directories that are to be bundled
#                 into the jar archive.
#
#***************************************************************************

PACKAGE     = pcp.translator
PACKAGE_LOC = pcp.translator

SOURCE = \
  AdditiveExpression.java \
  Arguments.java \
  ArrayInitializer.java \
  AssertStatement.java \
  BasicCastExpression.java \
  BasicForControl.java \
  BitwiseAndExpression.java \
  BitwiseNegationExpression.java \
  BitwiseOrExpression.java \
  BitwiseXorExpression.java \
  Block.java \
  BlockDeclaration.java \
  BooleanLiteral.java \
  BreakStatement.java \
  CallExpression.java \
  CaseClause.java \
  CastExpression.java \
  CatchClause.java \
  CharacterLiteral.java \
  ClassBody.java \
  ClassDeclaration.java \
  ClassLiteralExpression.java \
  CompilationUnit.java \
  ConcreteDimension.java \
  ConcreteDimensions.java \
  ConditionalExpression.java \
  ConditionalStatement.java \
  ConstructorDeclaration.java \
  ContinueStatement.java \
  Declaration.java \
  Declarator.java \
  Declarators.java \
  DefaultClause.java \
  DoWhileStatement.java \
  EqualityExpression.java \
  Expression.java \
  ExpressionList.java \
  ExpressionStatement.java \
  Extension.java \
  FieldDeclaration.java \
  FloatingPointLiteral.java \
  ForStatement.java \
  FormalParameter.java \
  FormalParameters.java \
  Implementation.java \
  ImportDeclaration.java \
  InstanceOfExpression.java \
  IntegerLiteral.java \
  InterfaceDeclaration.java \
  LabeledStatement.java \
  Literal.java \
  LogicalAndExpression.java \
  LogicalNegationExpression.java \
  LogicalOrExpression.java \
  MethodDeclaration.java \
  Modifiers.java \
  MultiplicativeExpression.java \
  NewArrayExpression.java \
  NewClassExpression.java \
  PackageDeclaration.java \
  PostfixExpression.java \
  PrimaryExpression.java \
  PrimaryIdentifier.java \
  PrimitiveType.java \
  QualifiedIdentifier.java \
  RelationalExpression.java \
  ReturnStatement.java \
  SelectionExpression.java \
  ShiftExpression.java \
  Statement.java \
  StringLiteral.java \
  SwitchClause.java \
  SwitchStatement.java \
  Symbol.java \
  SynchronizedStatement.java \
  ThisExpression.java \
  ThrowStatement.java \
  ThrowsClause.java \
  Translatable.java \
  TranslationVisitor.java \
  TryCatchFinallyStatement.java \
  Type.java \
  UnaryExpression.java \
  Variable.java \
  VariableInitializer.java \
  Visibility.java \
  VoidType.java \
  WhileStatement.java \
  Word.java  

JNI_SOURCE =

JAR_EXTRAS = 


#***************************************************************************
#
# Include common part of makefile
#
#***************************************************************************

ifdef OOP_ROOT
include $(OOP_ROOT)/Makerules

.PHONY : classes

classes:

endif
